#!/bin/bash
rm -f /tmp/tempfifo1
rm -f /tmp/a.out
mkfifo /tmp/tempfifo1 2>/dev/null
cat << 'EOF' > /tmp/tempfifo1 &



  .section  __TEXT,__text,regular,pure_instructions
  .globl  _main
  .align  4, 0x90
_main:
  pushq %rbp
  movq  %rsp, %rbp
  subq  $32, %rsp
  leaq  L_.str(%rip), %rax
  movl  $0, -4(%rbp)
  movl  %edi, -8(%rbp)
  movq  %rsi, -16(%rbp)
  movq  %rax, %rdi
  movb  $0, %al
  callq _printf
  xorl  %ecx, %ecx
  movl  %eax, -20(%rbp)
  movl  %ecx, %eax
  addq  $32, %rsp
  popq  %rbp
  retq

  .section  __TEXT,__cstring,cstring_literals
L_.str:
  .asciz  "Hi there!\n"



EOF

cat /tmp/tempfifo1 | gcc -x assembler -o /tmp/a.out -
/tmp/a.out
